In [16]:
import pandas as pd 

print("Pandas version:", pd.__version__)
print("Pandas library is imported successfully...!")

Pandas version: 3.0.3
Pandas library is imported successfully...!

In [ ]:
Data = {
    "Name": [
        "Het Soni",
    ],
    "Mobile Number": [
        9327983260
    ]
}

print("Data has been created")

Data = pd.DataFrame(Data)
display(Data)

Data has been created

       Name  Mobile Number
0  Het Soni     9327983260

In [13]:
Export_Data = Data.to_excel("leads.xlsx", index=False)

print("Data Exported to Excel successfully...!")

Data Exported to Excel successfully...!

In [14]:
# Check the Data
Check_Data = pd.read_excel(
    "./leads.xlsx"
    )

display(Check_Data)

       Name  Mobile Number
0  Het Soni     9327983260

In [15]:
# All Good...!